// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    alias(libs.plugins.androidApplication) apply false
    alias(libs.plugins.kotlinAndroid) apply false
}

allprojects {
    configurations.all {
        resolutionStrategy {
            force 'androidx.core:core:1.13.0'
            force 'androidx.core:core-ktx:1.13.0'
        }
    }
}