import java.util.Properties

plugins {
    alias(libs.plugins.androidApplication)
}

Properties properties = new Properties()
properties.load(project.rootProject.file("local.properties").newDataInputStream())

android {
    namespace 'com.example.rundraw_fe'
    compileSdk 34

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId "com.example.rundraw_fe"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        // 변수 설정
        buildConfigField "String", "OAUTH_URL", "\"${properties.getProperty("OAUTH_URL")}\""
        buildConfigField "String", "LOCAL_URL", "\"${properties.getProperty("LOCAL_URL")}\""
        manifestPlaceholders = [GOOGLE_MAP_KEY: properties.getProperty("GOOGLE_MAP_KEY")]
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    implementation "com.squareup.okhttp3:okhttp:4.12.0"
    implementation "com.squareup.retrofit2:retrofit:2.11.0"
    implementation "com.squareup.retrofit2:converter-gson:2.11.0"
    implementation 'com.google.android.gms:play-services-maps:18.2.0'

}